(** Audit the public implementation-to-Simplicity results after a full build. *)
Require Import C.jet_increment8_spec C.jet_one8_call C.jet_one8_general.
Require Import C.jet_increment8_general.
Require Import C.jet_one8_position C.jet_word_position.
Require Import C.jet_increment8_position C.jet_increment8_position_word.
Require Import C.jet_one8_crossing C.jet_crossing_word.
Require Import C.jet_increment8_cursors.
Require Import C.jet_add8_call.
Require Import C.jet_add8_spec C.jet_add8_word.
Require Import C.jet_write8_crossing_frame C.jet_crossing_byte.
Require Import C.jet_writeBit_high.
Require Import C.jet_carry_byte_crossing.
Require Import C.jet_increment8_crossing C.jet_add8_crossing C.jet_increment8_crossing_word.
Require Import C.jet_read8_crossing C.jet_read8_crossing_word.
Require Import C.jet_read8_two_words.
Require Import C.jet_read8_layout_total.
Require Import C.jet_writeBit_layout C.jet_write8_layout.
Require Import C.jet_write8_layout_total C.jet_one8_layout.
Require Import C.jet_writeBit_layout_total C.jet_carry_byte_layout.
Require Import C.jet_increment8_layout C.jet_add8_layout.
Print Assumptions eval_increment8_layout_matches_spec.
Print Assumptions eval_add8_layout_matches_spec.
Print Assumptions eval_writeBit_layout.
Print Assumptions write_bit_value_correct.
Print Assumptions write_bit_value_prefix.
Print Assumptions eval_carry_byte_layout.
Print Assumptions eval_write8_layout.
Print Assumptions eval_one8_layout_matches_spec.
Print Assumptions eval_writeBit_layout_raw.
Print Assumptions eval_write8_layout_non_crossing_raw.
Print Assumptions eval_write8_layout_crossing_raw.
Print Assumptions eval_read8_layout.
Require Import C.jet_output9 C.jet_carry_byte_position.
Require Import C.jet_increment8_frames C.jet_add8_frames.
Require Import C.jet_increment8_input_layout C.jet_add8_input_layout.
Print Assumptions eval_increment8_input_layout_matches_spec.
Print Assumptions eval_add8_input_layout_matches_spec.
Print Assumptions eval_increment8_frames_matches_spec.
Print Assumptions eval_add8_frames_matches_spec.
Print Assumptions eval_carry_byte_output9.
Print Assumptions carry_byte_at_decode.
Require Import C.jet_increment8_two_words C.jet_add8_two_words.
Print Assumptions eval_increment8_two_words_matches_spec.
Print Assumptions eval_add8_two_words_matches_spec.
Print Assumptions eval_read8_two_words.
Print Assumptions eval_read8_crossing.
Print Assumptions read8_crossing_denotes_slice.
Print Assumptions eval_increment8_crossing_matches_spec.
Print Assumptions eval_add8_crossing_matches_spec.
Print Assumptions increment8_carry_byte_spec.
Print Assumptions eval_carry_byte_crossing.
Print Assumptions eval_writeBit_false_high.
Print Assumptions eval_writeBit_true_high.
Print Assumptions eval_write8_crossing_frame.
Print Assumptions crossing_byte_projection.
Print Assumptions eval_add8_cursors_matches_spec.
Print Assumptions add8_values_denote_spec.
Print Assumptions add8_spec_initial.
Print Assumptions eval_add8_position_call.
Print Assumptions eval_increment8_cursors_matches_spec.
Print Assumptions eval_one8_crossing_matches_spec.
Print Assumptions crossing_byte_one.
Print Assumptions eval_increment8_position_matches_spec.
Print Assumptions increment8_word_at_decode.
Print Assumptions eval_one8_position_matches_spec.
Print Assumptions put_byte_projection.
Print Assumptions eval_increment8_frame_matches_spec.
Print Assumptions eval_one8_frame_matches_spec.
Print Assumptions eval_increment8_matches_spec.
Print Assumptions eval_one8_initial_matches_spec.
Print Assumptions increment8_output_denotes_spec.
Print Assumptions increment8_spec_initial.
