(** Generated byte writer at arbitrary physical frame and backing-word addresses. *)
From Coq Require Import ZArith List Lia.
From compcert Require Import Coqlib Integers AST Ctypes Cop Clight Maps.
From compcert Require Import ClightBigstep Memory Events Globalenvs.
Require Import C.jets C.jet_exec C.jet_frame_layout C.jet_write_layout C.jet_frame_access.
Require Import C.jet_frame_arith C.jet_word_bits C.jet_write8_position C.jet_write8_crossing_general.
Require Import C.jet_crossing_arith.
Import Values Mem Ctypes ListNotations Clightdefs Clightdefs.ClightNotations.
Local Open Scope Z_scope.
Local Transparent Archi.ptr64.

Definition le_write8_layout (bf : block) base (x : int) : temp_env :=
  PTree.set _x (Vint x) (PTree.set _frame (Vptr bf (Ptrofs.repr base))
    (create_undef_temps f_simplicity_write8.(fn_temps))).

Lemma entry_write8_layout m bf base x :
  function_entry2 ge0 f_simplicity_write8 [Vptr bf (Ptrofs.repr base); Vint x]
    m empty_env (le_write8_layout bf base x) m.
Proof.
  constructor.
  - constructor.
  - repeat constructor; simpl; intuition discriminate.
  - intros id1 id2 H1 H2 Heq. simpl in H1, H2. subst id2.
    repeat match goal with H : _ \/ _ |- _ => destruct H end.
    all: vm_compute in *; congruence.
  - constructor.
  - reflexivity.
Qed.

Ltac bytelayout_stmt :=
  lazymatch goal with
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Ssequence _ _) _ _ _ _ =>
      eapply exec_Sseq_1 with (t1 := E0) (t2 := E0); [bytelayout_stmt | bytelayout_stmt]
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Sset _ _) _ _ _ _ =>
      apply exec_set; writelayout_expr
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Sifthenelse _ _ _) _ _ _ _ =>
      first [eapply exec_Sifthenelse with (v1 := Vint Int.zero) (b := false);
        [writelayout_expr | reflexivity | apply exec_Sskip]
      | eapply exec_Sifthenelse with (v1 := Vint Int.one) (b := true);
        [writelayout_expr | reflexivity | bytelayout_stmt]]
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Swhile _ _) _ _ _ _ =>
      unfold Swhile; bytelayout_stmt
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Sloop _ _) _ _ _ _ =>
      eapply exec_Sloop_stop1 with (out' := Out_break);
      [eapply exec_Sseq_2;
        [eapply exec_Sifthenelse with (v1 := Vint Int.zero) (b := false);
          [writelayout_expr | reflexivity | apply exec_Sbreak]
        | discriminate]
      | constructor]
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Scall _ (Evar _LSBclear _) _) _ _ _ _ =>
      writelayout_call f_LSBclear symbol_LSBclear funct_LSBclear
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Scall _ (Evar _LSBkeep _) _) _ _ _ _ =>
      writelayout_call f_LSBkeep symbol_LSBkeep funct_LSBkeep
  | |- ClightBigstep.exec_stmt _ _ _ _ _ (Sassign _ _) _ _ _ _ => writelayout_assign
  end.

Lemma eval_write8_layout_non_crossing_raw m mw mf bf base bw edge cursor old x :
  frame_base_valid base -> 8 <= cursor <= Int64.max_unsigned ->
  8 <= write_word_shift cursor ->
  0 <= edge -> write_word_address edge cursor + 8 <= Ptrofs.max_unsigned ->
  frame_fields_at m bf base bw edge cursor ->
  Mem.load Mint64 m bw (write_word_address edge cursor) = Some (Vlong old) ->
  Mem.store Mint64 m bw (write_word_address edge cursor)
    (Vlong (put_byte (write_word_shift cursor) old (Int64.repr (Int.unsigned x)))) = Some mw ->
  Mem.store Mint64 mw bf (base + 8) (Vlong (Int64.repr (cursor - 8))) = Some mf -> bf <> bw ->
  ClightBigstep.Clight2.eval_funcall ge0 m (Internal f_simplicity_write8)
    [Vptr bf (Ptrofs.repr base); Vint x] E0 mf Vundef.
Proof.
  intros HB HC HN HE HA [HF HO] HW SW SF HD.
  pose proof (write_layout_index cursor ltac:(lia)) as [HQ [HK [Hsub [Hdiv [Hmod Hwidth]]]]].
  pose proof (write_layout_pointer edge ((cursor - 1) / 64) HQ HE
    ltac:(unfold write_word_address in HA; lia)) as Hptr.
  fold (write_word_address edge cursor) in Hptr.
  assert (Haddr : Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor)) =
      write_word_address edge cursor).
  { apply Ptrofs.unsigned_repr. unfold write_word_address in *; lia. }
  assert (HWp : Mem.load Mint64 m bw
      (Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor))) = Some (Vlong old))
    by (rewrite Haddr; exact HW).
  assert (SWp : Mem.store Mint64 m bw
      (Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor)))
      (Vlong (put_byte (write_word_shift cursor) old (Int64.repr (Int.unsigned x)))) = Some mw)
    by (rewrite Haddr; exact SW).
  assert (HOw : Mem.load Mint64 mw bf (base + 8) = Some (Vlong (Int64.repr cursor))).
  { erewrite Mem.load_store_other; [exact HO|exact SW|auto]. }
  pose proof (cursor_no_cross (write_word_shift cursor) ltac:(lia)) as Hcross.
  pose proof (cursor_sub (write_word_shift cursor) 8 ltac:(lia) ltac:(lia)) as Hshift_sub.
  assert (Hshift : Int64.ltu (Int64.repr (write_word_shift cursor - 8)) Int64.iwordsize = true).
  { unfold Int64.ltu. rewrite cursor_unsigned by lia.
    change ((if zlt (write_word_shift cursor - 8) 64 then true else false) = true).
    rewrite zlt_true by lia; reflexivity. }
  assert (Hfinal : Int64.sub (Int64.repr cursor) (Int64.repr 8) = Int64.repr (cursor - 8)).
  { unfold Int64.sub. rewrite (Int64.unsigned_repr cursor) by lia. reflexivity. }
  unfold put_byte in SWp.
  eapply ClightBigstep.eval_funcall_internal
    with (e := empty_env) (le1 := le_write8_layout bf base x) (m1 := m)
      (m2 := mf) (out := Out_normal) (vres := Vundef).
  - apply entry_write8_layout.
  - unfold f_simplicity_write8; cbn [fn_body]. timeout 10 bytelayout_stmt.
  - reflexivity.
  - reflexivity.
Qed.

Lemma eval_write8_layout_crossing_raw m mh mo ml mf bf base bw edge cursor k oldhigh oldlow x :
  frame_base_valid base -> 8 <= cursor <= Int64.max_unsigned ->
  1 <= k <= 7 -> write_word_shift cursor = k ->
  0 <= edge -> 8 <= write_word_address edge cursor ->
  write_word_address edge cursor + 8 <= Ptrofs.max_unsigned ->
  frame_fields_at m bf base bw edge cursor ->
  Mem.load Mint64 m bw (write_word_address edge cursor) = Some (Vlong oldhigh) ->
  Mem.store Mint64 m bw (write_word_address edge cursor)
    (Vlong (crossing_high k oldhigh x)) = Some mh ->
  Mem.load Mint64 mh bf (base + 8) = Some (Vlong (Int64.repr cursor)) ->
  Mem.store Mint64 mh bf (base + 8) (Vlong (Int64.repr (cursor - k))) = Some mo ->
  Mem.load Mint64 mo bw (write_word_address edge cursor - 8) = Some (Vlong oldlow) ->
  Mem.store Mint64 mo bw (write_word_address edge cursor - 8)
    (Vlong (crossing_low k x)) = Some ml ->
  Mem.load Mint64 ml bf (base + 8) = Some (Vlong (Int64.repr (cursor - k))) ->
  Mem.store Mint64 ml bf (base + 8) (Vlong (Int64.repr (cursor - 8))) = Some mf ->
  ClightBigstep.Clight2.eval_funcall ge0 m (Internal f_simplicity_write8)
    [Vptr bf (Ptrofs.repr base); Vint x] E0 mf Vundef.
Proof.
  intros HB HC HK HKdef HE HA0 HA [HF HO] HH SH HOh SO HL SL HOl SF.
  pose proof (write_layout_index cursor ltac:(lia)) as [HQ [HK' [Hsub [Hdiv [Hmod Hwidth]]]]].
  rewrite HKdef in Hwidth.
  pose proof (write_layout_pointer edge ((cursor - 1) / 64) HQ HE
    ltac:(unfold write_word_address in HA; lia)) as Hptr.
  fold (write_word_address edge cursor) in Hptr.
  assert (Haddr : Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor)) =
      write_word_address edge cursor) by (apply Ptrofs.unsigned_repr; lia).
  assert (HaddrL : Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor - 8)) =
      write_word_address edge cursor - 8) by (apply Ptrofs.unsigned_repr; lia).
  assert (HptrL : Ptrofs.sub (Ptrofs.repr (write_word_address edge cursor)) (Ptrofs.repr 8) =
      Ptrofs.repr (write_word_address edge cursor - 8)).
  { unfold Ptrofs.sub. rewrite Haddr. reflexivity. }
  assert (HHp : Mem.load Mint64 m bw
      (Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor))) = Some (Vlong oldhigh))
    by (rewrite Haddr; exact HH).
  assert (HLp : Mem.load Mint64 mo bw
      (Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor - 8))) = Some (Vlong oldlow))
    by (rewrite HaddrL; exact HL).
  assert (SHp : Mem.store Mint64 m bw
      (Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor)))
      (Vlong (crossing_high k oldhigh x)) = Some mh) by (rewrite Haddr; exact SH).
  assert (SLp : Mem.store Mint64 mo bw
      (Ptrofs.unsigned (Ptrofs.repr (write_word_address edge cursor - 8)))
      (Vlong (crossing_low k x)) = Some ml) by (rewrite HaddrL; exact SL).
  pose proof (byte_crossing_arithmetic_holds k HK) as HArith.
  unfold byte_crossing_arithmetic in HArith.
  destruct HArith as [HAdiv [HAwidth [Hcross [Hsub8 [HS64 [Hshift32 [HShr [Hshiftsub
    [Hshift [Hstop [HZ HO1]]]]]]]]]]].
  assert (Hfirst : Int64.sub (Int64.repr cursor) (Int64.repr k) = Int64.repr (cursor - k)).
  { unfold Int64.sub. rewrite (Int64.unsigned_repr cursor) by lia.
    rewrite cursor_unsigned by lia; reflexivity. }
  assert (Hfinal : Int64.sub (Int64.repr (cursor - k)) (Int64.repr (8 - k)) = Int64.repr (cursor - 8)).
  { unfold Int64.sub. rewrite (Int64.unsigned_repr (cursor - k)) by lia.
    rewrite cursor_unsigned by lia. f_equal; lia. }
  unfold crossing_high in SHp. unfold crossing_low in SLp.
  eapply ClightBigstep.eval_funcall_internal
    with (e := empty_env) (le1 := le_write8_layout bf base x) (m1 := m)
      (m2 := mf) (out := Out_normal) (vres := Vundef).
  - apply entry_write8_layout.
  - unfold f_simplicity_write8; cbn [fn_body]. timeout 10 bytelayout_stmt.
  - reflexivity.
  - reflexivity.
Qed.
